### ISSUE TITLE
Can't compile on macos

### ISSUE THREAD

**Issue by Hperigo** [vassvik/odin-glfw#6]
Hi, I tried to compile this repo on MacOs and it failed:

here are the errors that I got: 
```/Users/henrique/Documents/Dev/odin/Odin/shared/odin-glfw/bindings/bindings.odin(10:9) Undeclared name: glfw
/Users/henrique/Documents/Dev/odin/Odin/shared/odin-glfw/bindings/bindings.odin(10:9) Undeclared name: glfw
/Users/henrique/Documents/Dev/odin/Odin/shared/odin-glfw/bindings/bindings.odin(10:9) Undeclared name: glfw
/Users/henrique/Documents/Dev/odin/Odin/shared/odin-glfw/bindings/bindings.odin(10:9) Undeclared name: glfw
/Users/henrique/Documents/Dev/odin/Odin/shared/odin-glfw/bindings/bindings.odin(10:9) Undeclared name: glfw
/Users/henrique/Documents/Dev/odin/Odin/shared/odin-glfw/bindings/bindings.odin(10:9) Undeclared name: glfw
/Users/henrique/Documents/Dev/odin/Odin/shared/odin-glfw/bindings/bindings.odin(10:9) Undeclared name: glfw
/Users/henrique/Documents/Dev/odin/Odin/shared/odin-glfw/bindings/bindings.odin(10:9) Undeclared name: glfw
/Users/henrique/Documents/Dev/odin/Odin/shared/odin-glfw/bindings/bindings.odin(10:9) Undeclared name: glfw
/Users/henrique/Documents/Dev/odin/Odin/shared/odin-glfw/bindings/bindings.odin(10:9) Undeclared name: glfw
/Users/henrique/Documents/Dev/odin/Odin/shared/odin-glfw/bindings/bindings.odin(10:9) Undeclared name: glfw
/Users/henrique/Documents/Dev/odin/Odin/shared/odin-glfw/bindings/bindings.odin(10:9) Undeclared name: glfw
/Users/henrique/Documents/Dev/odin/Odin/shared/odin-glfw/bindings/bindings.odin(10:9) Undeclared name: glfw
/Users/henrique/Documents/Dev/odin/Odin/shared/odin-glfw/bindings/bindings.odin(10:9) Undeclared name: glfw
/Users/henrique/Documents/Dev/odin/Odin/shared/odin-glfw/bindings/bindings.odin(10:9) Undeclared name: glfw
/Users/henrique/Documents/Dev/odin/Odin/shared/odin-glfw/bindings/bindings.odin(10:9) Undeclared name: glfw
/Users/henrique/Documents/Dev/odin/Odin/shared/odin-glfw/bindings/bindings.odin(10:9) Undeclared name: glfw
/Users/henrique/Documents/Dev/odin/Odin/shared/odin-glfw/bindings/bindings.odin(10:9) Undeclared name: glfw
/Users/henrique/Documents/Dev/odin/Odin/shared/odin-glfw/bindings/bindings.odin(10:9) Undeclared name: glfw
/Users/henrique/Documents/Dev/odin/Odin/shared/odin-glfw/bindings/bindings.odin(10:9) Undeclared name: glfw
/Users/henrique/Documents/Dev/odin/Odin/shared/odin-glfw/bindings/bindings.odin(10:9) Undeclared name: glfw```

weirdly, they are all the same... any tips on this? 
thanks!

**Comment by vassvik** [comment]
There have been some recent experiments with the import names, so that's likely the issue. I'll look into it.

**Comment by vassvik** [comment]
I was mistaken. The problem is that I have not added the actual linking to the appropriate library for macos. See https://github.com/vassvik/odin-glfw/blob/master/bindings/bindings.odin#L5-L6
If you know what to link to on OSX let me know.

**Comment by Hperigo** [comment]
yeah, compilling glfw and adding: 
```when os.OS == "osx"  do foreign import glfw {"../lib/glfw3.a"};``` in the file/line  you mentioned solved the compile issue, thanks!

now I have another question, this is my code:

```
package main

import "shared:odin-glfw"


main :: proc() {

    glfw.Init();

}
```

but I keep getting this error:
```/Users/henrique/Documents/Dev/odin/Odin/examples/gl/main.odin(11:5) 'Init' is not declared by 'glfw' ```

any pointers? also, any example I can take a look at?

**Comment by vassvik** [comment]
I have recently refactored the bindings into more of a wrapper, where it uses Odin types and semantics where it can, and also  matching the preferred naming schemes.

So what you're looking for is `glfw.init`, `glfw.create_window`, etc.

Direct *bindings* are there as well, but import `odin-glfw/bindings` instead. This uses the C names and binds directly to C types. The wrapper is recommended though, just replace `glfwFooBar` with `glfw.foo_bar`, and don't be too scared to just look at the files :]

**Comment by vassvik** [comment]
Would getting glfw from homebrew work the same? If so, what would you link against? Building it yourself can be a bit annoying if there are easier options. I don't have a mac, so it's hard to know for me

**Comment by Hperigo** [comment]
Hi, yeah, installing it from homebrew worked and using `glfw.init` (yey!), only had to change that line to: 
```when os.OS == "osx"  do foreign import glfw {"system:glfw"};```

now, I'm confused, why does the `bindings.odin` has *CamelCase* functions and the actual function call is *snake_case*?
```
/*** Functions ***/
@(default_calling_convention="c", link_prefix="glfw")
foreign glfw {
    Init      :: proc() -> i32 ---;
    Terminate :: proc() ---;

    InitHint  :: proc(hint, value: i32) ---;

    GetVersion :: proc(major, minor, rev: ^i32) ---;
    GetError   :: proc(description: ^cstring) -> i32 ---;

    GetPrimaryMonitor      :: proc() -> Monitor_Handle ---;
    GetMonitors            :: proc(count: ^i32) -> ^Monitor_Handle ---;
    GetMonitorPos          :: proc(monitor: Monitor_Handle, xpos, ypos: ^i32) ---;
    GetMonitorPhysicalSize :: proc(monitor: Monitor_Handle, widthMM, heightMM: ^i32) ---;
    GetMonitorContentScale :: proc(monitor: Monitor_Handle, xscale, yscale: ^f32) ---;

    SetMonitorUserPointer :: proc(monitor: Monitor_Handle, pointer: rawptr) ---;
    GetMonitorUserPointer :: proc(monitor: Monitor_Handle) -> rawptr ---;

    GetVideoMode :: proc(monitor: Monitor_Handle) -> ^Vid_Mode ---;
    SetGamma     :: proc(monitor: Monitor_Handle, gamma: f32) ---;
    GetGammaRamp :: proc(monitor: Monitor_Handle) -> ^Gamma_Ramp ---;
...
```
Apologies for the amount of questions and thanks for the help! I'm pretty new to odin...

**Comment by vassvik** [comment]
For wrappers I like to conform to Odin's conventions, and keep bindings as close to the C version as possible. Hence, the naming schemes here.

**Comment by Hperigo** [comment]
A sorry, I was only looking at the files inside the bindings folder, not the odin-glfw root. anyway, thanks again for the help!
